language: scala
scala:
- 2.10.2
jdk:
- oraclejdk7
- openjdk6
script: sbt -Dbuild.publish.user=${SONATYPE_USER} -Dbuild.publish.password=${SONATYPE_PASS} ++${TRAVIS_SCALA_VERSION} test `if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then echo "publish";  fi`
env:
  global:
  - secure: zVnVXV4Fq08mQ1AYXhmA6V2SUIn7NcUXl6QHB0KnwROMLBxAdbenNYzeJkD2lnTiOy/OlvQ8wOBZdBXMvwxOq6pOmdU4RfK49jk22+OAc25Nro+Sue9Exi12uZO8Y705Xk4PJAmn4bFSnV+ykrHdhICvCSqdyUhzo5VPGk+fqNw=
  - secure: E4kdKRZjZ6g86+S8Hjq9mUuuUjab/51Wp4gxiBViyUqP0qps5nRm/V1ASfyZL0SBUd96lMwaCoJAYr0vlS++sEwR7u4pZHgQSXuGhmnYfSnLwQ48QHVoRJEg0Ap43oUNcW27Meri2zTa6eDF87e83LfLduvuHUVZql3bh4xkOVY=
